all:
	g++ -c ./TDA-Lista-Vendedores/listaVendedores.cpp
	g++ -c ./TDA-Lista-Clientes/listaClientes.cpp
	g++ -c main.cpp
	g++ -o ejecutable listaVendedores.o listaClientes.o main.o
	rm *.o
	./ejecutable